theme: jekyll-theme-minimal
title: Violence, Instability, and Peace (VIP) Workshop
description: A virtual workshop series for conflict and peace scholars to share their research.
logo: /violence.jpeg
